import { Eye, EyeOff } from "lucide-react";
import { useState } from "react";

const generateIdOrName = ({ label }: any) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `input-${Math.random().toString(36).substr(2, 9)}`;
};

interface InputProps {
  type?: string;
  id?: string;
  name?: string;
  label?: string;
  placeholder?: string;
  icon?: React.ReactNode;
  tooltip?: React.ReactNode;
  errorMessage?: string;
  className?: string;
  register?: any;
  required?: boolean;
  [key: string]: any;
}

const Input = ({
  type = "text",
  id,
  name,
  label = "",
  placeholder = "",
  icon,
  tooltip,
  errorMessage,
  className = "",
  register,
  required,
  ...props
}: InputProps) => {
  const [isSecureEntry, setIsSecureEntry] = useState(true);

  const autoGeneratedId = id || generateIdOrName({ label });
  const autoGeneratedName = name || generateIdOrName({ label });

  return (
    <div className={`relative w-full ${className}`}>
      {label && (
        <label
          htmlFor={autoGeneratedId}
          className="block text-white mb-2 text-sm"
        >
          {label}
        </label>
      )}

      <div className="relative">
        {/* Left icon */}
        {icon && (
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-white/50">
            {icon}
          </span>
        )}

        <input
          {...(register ? register(autoGeneratedName, { required }) : {})}
          {...props}
          type={
            type === "password" ? (isSecureEntry ? "password" : "text") : type
          }
          id={autoGeneratedId}
          name={autoGeneratedName}
          placeholder={placeholder}
          className={`w-full bg-white/10 border border-white/20 focus:border-white text-white placeholder:text-white/40 rounded-2xl px-6 py-5 text-base outline-none transition-all
          ${icon ? "pl-12" : ""}
          ${errorMessage ? "border-red-400" : ""}
          `}
        />

        {/* Tooltip */}
        {tooltip && (
          <span className="absolute right-4 top-1/2 -translate-y-1/2 text-white/50">
            {tooltip}
          </span>
        )}

        {/* Password toggle */}
        {type === "password" && (
          <span
            onClick={() => setIsSecureEntry((prev) => !prev)}
            className="absolute right-4 top-1/2 -translate-y-1/2 cursor-pointer text-white/60"
          >
            {isSecureEntry ? <Eye size={20} /> : <EyeOff size={20} />}
          </span>
        )}
      </div>

      {/* Error */}
      {errorMessage && (
        <p className="text-red-400 text-sm mt-1">{errorMessage}</p>
      )}
    </div>
  );
};

export default Input;
